modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "pyrite"
version = "${version}"
displayName = "Pyrite"
authors = "cassiancc"
description = '''
Variations of Vanilla blocks, including dyed wood, dyed bricks, new material blocks and more to complete your colourful builds.
'''
logoFile = "assets/pyrite/icon.png"

[[dependencies.pyrite]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pyrite]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pyrite]]
modId = "architectury"
type = "required"
versionRange = "[13.0.1,)"
ordering = "AFTER"
side = "BOTH"